version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "1111:1111"
    
volumes: 
  postgres-data: